name: Tenant Snapshot
on:
  workflow_dispatch:
    inputs:
      directory:
        description: 'Target artifact directory (relative from Git repository root)'
        required: false
      includedIds:
        description: 'Included package Ids (optional)'
        required: false
      excludedIds:
        description: 'Excluded package Ids (optional)'
        required: false    
      draft:
        description: '(Optional) Draft handling'
        type: choice
        options:
          - SKIP
          - ADD
          - ERROR
        required: false
      message:
        description: '(Optional) Commit message'
        required: false
permissions:
  contents: write

jobs:
  backup:
    runs-on: ubuntu-latest
    container:
      image: engswee/flashpipe:latest
      env:
        LOG_LEVEL: DEBUG


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync artifacts from tenant to GitHub
        uses: engswee/flashpipe-action/snapshot@v1
        with:
          tmn-host: ntt-pi-dev.it-cpi001.cfapps.eu10.hana.ondemand.com
          oauth-host: ntt-pi-dev.authentication.eu10.hana.ondemand.com
          oauth-clientid: sb-72493dbb-f9e3-43dc-ba00-d32302caccd2!b77644|it!b16077
          oauth-clientsecret: 9a205cae-c9c9-4e75-9aab-f36bc05edcfe$ofavsuffzxGYkYTMtiuQRmuwOyV5UO_zy5Pgxtcz-XM=
          draft-handling: ADD
          git-commit-msg: "Snapshot from Tenant #3"
